export const meta = {
  name: 'Research and Report',
  description: 'Research and Report — unbounded best-first web crawl steered by a BRAINER (the brain) over a persistent id-keyed rabbit-hole store. haiku scout seeds rabbit-holes → opus PROSPECTOR names the high-value authoritative source venues for the topic → [the brainer looks up OR originates the rabbit-holes worth pursuing AND assigns each its relevant venue subset → parallel haiku lane-researchers pursue (preferring their assigned venues) → the brainer returns delta updates (rescore / add / lookupNext / rename / drop), maintains a running resultSoFar, decides done; in goal mode a sentinel may reopen a premature done and force one more wave] until done / rabbithole-dry / wave hard-cap (15) → FINALIZE: an opus INITIATOR plans the finish for the query → a sonnet refine pass fact-checks + hardens the load-bearing facts against the sources → an optional sequential opus COMPUTEMENT chain derives the answer (writing + running code, propagating error bars) when it must be built → an opus aggregator writes the 7-section report. Pursued-archive (no delete-on-pursue) + pursued memory; scoreHistory rides natively on each rabbit-hole id. Two modes: goal (satisficing) / collect (exhaustive). Returns per-wave markdown + refinement + report + _frontier.json.',
  phases: [
    { title: 'Scout', detail: 'the seed: haiku scout maps the landscape (fetch sources with the rabbit-hole footer) → opus prospector names the high-value authoritative source venues → the brainer scores the scout rabbit-holes, assigns each its venue subset, and looks up the first wave' },
    { title: 'Research', detail: 'each wave: the brainer looks up OR originates the rabbit-holes worth pursuing + assigns each its venue subset → parallel haiku lane-researchers pursue (preferring assigned venues) → the brainer returns delta updates (rescore / add / lookupNext), maintains the running resultSoFar (knows pursued + score trajectory), decides done; goal-mode sentinel can force one more wave on a real gap' },
    { title: 'Finalize', detail: 'an opus INITIATOR shapes the finish to the query → refinement (a sonnet refine agent fact-checks + hardens each load-bearing fact against the sources) → computement (optional: a sequential opus chain that DERIVES the answer — writing + running code, propagating error bars — when the answer must be built) → an opus aggregator writes the report' },
    { title: 'Debug', detail: 'opt-in (arg.debug): a final Debug & Analysis agent aggregates metrics + run log + raw agent I/O into one _debug.md — incl. prospector→researcher venue-utilization and any arg.debugPrompt question' },
  ],
}
